server:
  port: 9090

spring:
  application:
    name: LOGIN-SERVICE



  jpa:
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/USER?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

#spring.jpa.show-sql: true
---
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
  tracing:
    sampling:
      probability: 1.0

spring:
  zipkin:
    baseUrl: http://localhost:9411/
  main:
    allow-circular-references: true
